# Generated by Django 5.0.2 on 2024-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
