# Generated by Django 5.0.2 on 2024-02-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.CharField(default="", max_length=225),
        ),
    ]
